name: Android Dev CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Clone Flutter repository with dev channel
      uses: actions/checkout@v2
      with:
        repository: 'flutter/flutter'
        ref: 'dev'
        path: 'flutter'
        fetch-depth: 0
    - name: Add Flutter to the PATH
      run: echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH
    - name: Run Flutter doctor
      run: flutter doctor -v
    - name: Get packages for the Flutter project
      run: cd acnh_module && flutter pub get && cd ..
    - name: build flutter project
      run: flutter build aar
      working-directory: acnh_module
    - name: Build with Gradle
      run: bash gradlew assembleDebug
#    - name: upload apk
#      uses: actions/upload-artifact@v2
#      with:
#        name: build
#        path: app/build/outputs/apk/debug/
